### ISSUE TITLE
Porosity Calculation

### ISSUE THREAD

**Issue by sukrumerey** [PMEAL/OpenPNM#1003]
How can we calculate porosity of a porous media via OpenPNM?

**Comment by ma-sadeghi** [comment]
I don't think we have a built-in function for that. But you can simply add up all the throat and pore volumes and divide it by the total volume. Here's an example for Cubic networks:

```
import openpnm as op

net = op.network.Cubic(shape=[10, 10, 10], spacing=1e-4, name='net')
geom = op.geometry.StickAndBall(network=net, pores=net.Ps, throats=net.Ts)

vol_total = (net._shape * net._spacing).prod()
vol_pores = geom['pore.volume'].sum()
vol_throats = geom['throat.volume'].sum()
porosity = (vol_pores + vol_throats) / vol_total * 100
print('Porosity (%):', porosity)

>>> Porosity (%): 10.1089548254
```

**Comment by ma-sadeghi** [comment]
Note that the above code snippet only works for 3D networks. We're in the process of adding 2D support to `OpenPNM`. Stay tuned.

**Comment by sukrumerey** [comment]
Dear @ma-sadeghi @jgostick thank you very much. Yes I want to use it for 3D system.

regards

**Comment by jgostick** [comment]
The reason we can't offer a porosity method is that it's often difficult to infer the actual domain size.  We only know the location of the pores, but not the 'outer' edge of the solid material.  

I will also add that @ma-sadeghi calculation of `vol_total` only works for Cubic networks (only they have the _shape and _spacing attributes) and we've also gotten rid of this V2.  You'll have to vol_total, or bulk volume by hand.

**Comment by Ahmedsf2019** [comment]
Where can I find the source code of the equation you calculate the porosity?

**Comment by jgostick** [comment]
We don't have a function/algorithm for this.  You need to craft if yourself since we cannot reliable calculate it for several reason. 
1.  We do not know the actual boundary of the domain, as I mentioned above
2. We cannot be sure that the pore and throat volumes are calculated correctly, with no overlaps or gaps.  

Technically you could do something as simple as this:

```
Vp = pn['pore.volume'].sum()
Vt = pn['throat.volume'].sum()
Vb = Lx*Ly*Lz
porosity = (Vp + Vt)/Vb
```

But this strongly depends on how carefully you calculate 'pore.volume' and 'throat.volume'.

**Comment by xu-kai-xu** [comment]
@jgostick  @ma-sadeghi, hi, I guess just use the following method to calculate porosity will get larger value than the actual one.  In built-in StickandBall model, `pore.volume` and `throat.volume` are calculated with `diameters`. This means, there may be some space in which pores and throats are intersected.

Then, the built-in model has parameters like `throat.conduit_length.pore1`, `throat.conduit_length.pore2`, `throat.conduit_length.throat`. The three parameters are calculated after `throat.endpoints`. So, I think using the three conduit lengths will get a  more accurate porosity. 

But it is hard to get the conduit_length for pores because they are arranged as the order of throats. 

What do you think about that?

> I don't think we have a built-in function for that. But you can simply add up all the throat and pore volumes and divide it by the total volume. Here's an example for Cubic networks:
> 
> ```
> import openpnm as op
> 
> net = op.network.Cubic(shape=[10, 10, 10], spacing=1e-4, name='net')
> geom = op.geometry.StickAndBall(network=net, pores=net.Ps, throats=net.Ts)
> 
> vol_total = (net._shape * net._spacing).prod()
> vol_pores = geom['pore.volume'].sum()
> vol_throats = geom['throat.volume'].sum()
> porosity = (vol_pores + vol_throats) / vol_total * 100
> print('Porosity (%):', porosity)
> 
> >>> Porosity (%): 10.1089548254
> ```

**Comment by jgostick** [comment]
The main issue is actually finding vol_total.  We have no way of knowing what the domain boundaries are, as we only track pore locations and sizes.  Regarding overlapping pores and throats, that is an important issue to, but it solvable.

**Comment by xu-kai-xu** [comment]
@jgostick, about the totol volume, can you use `pore.coords` for calculation? According to the coordinates, you can get the min and max values at each axis (if a xyz coordinate system). Then, the total volume may be confirmed.

**Comment by jgostick** [comment]
That misses the volume between the pores and the domain boundary.
