### ISSUE TITLE
questions about the advanced tutorial

### ISSUE THREAD

**Issue by xu-kai-xu** [PMEAL/OpenPNM#1196]
i am learnin the advanced tutorial. i find in th 143 cells(or something else labeled 143), a method is supplied to draw the drainage curve `plot_drainage_curve`, and get data `get_drainage_data`. but i can not find it in the method of inv, i just find `plot_intrusion_curve` and `get_intrusion_data`. maybe the name of the method has changed since the update of 2.0? and i got a plot of 5 points rather than 25 points. did something goes wrong?, i saw that the `run` method would get 25 points to generate the plot.
![001](https://user-images.githubusercontent.com/44153643/51042999-922ce800-15f8-11e9-8f9b-b40c36279ef5.png)

and the final relative permeability is [nan].  i do not understand what it means. is that wrong?

**Comment by jgostick** [comment]
I is called ``plot_intrusion_curve`` now, when using the Porosimetry class.  If your network is small then the the curve will not look good.  Also, because the graph uses a log axis the first point at 0,0 goes off to infinity on the left side of the graph which makes it look like the curve starts at S>0.  I have actually fixed in this in a PR, but it's not merged yet.
