### ISSUE TITLE
User question on Porosimetry

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1333]
I recently received a question about `Porosimetry`, since I'm not really familiar with it, I'll post it here. Here's the question:

> I have question about figure attached with this mail. I also attached the code with the mail. The problem is about the first part of capillary pressure curve, why does openpnm start test at Pc=0 and Snw(mercury)= 0.03? I get data with get_intrusion_data. Figure also show the problem, I mean threshold pressure doesn't exist. another question is does mercury invade air or just enter in vacuum pore?

![Capture2](https://user-images.githubusercontent.com/14086031/66606776-d269c880-eb80-11e9-908c-33af5ccbf92b.JPG)

[Here](https://gist.github.com/ma-sadeghi/b0bc9d25ed8696a05eb49f0c2f0f8419)'s the code.

**Comment by jgostick** [comment]
That non-zero starting saturation is an artifact.  In the Porosimetry class we start by setting all the inlet pores to invaded.  If these pores are proper boundary pores, then all is good.  If however, the user sets the inlets at REAL pores these have volume, hence the non-zero starting saturation.  We have since changed the algorithm to not do this.  The new way is actually less robust theoretically but less prone to this error.

To answer the second part, the mercury invades into a vacuum.  We don't consider the properties of the defending phase, and do not allow trapping, just like a real porosimetry experiment.  Using invasion percolation allows more options like this.

**Comment by saeidabd** [comment]
I appreciate that. It really help me finding out.
