### ISSUE TITLE
Non-invasively updating physics inside iterative algorithms

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1354]
Currently, we store properties that need to be updated after each iteration in iterative algorithms in `alg.settings.iterative_props`. The problem is that unless we invasively update `phase` w/ new values after each iteration, `update_iterative_props` doesn't do anything.

I think we used to do that, but is there a non-invasive way of regenerating phase and physics without invoking `phase.update(alg.results())`?

**Comment by jgostick** [comment]
This has always bothered, but we never came up with a good solution.  The solution would probably involve having the algorithm class somehow call the iterative models manually, and accept the returned arrays, rather than having openpnm do it with ``regenerate_models``.  But this doesn't help with the fact that the results are needed on the phase object during the model regeneration.  In other words, If we don't push the results back to the phase, then the models have nothing to iterate on.

**Comment by jgostick** [comment]
Another option is to clone the phase within the algorithm, then proceed as normal.  Need to think on it for a while, but it's not a terrible idea.

**Comment by ma-sadeghi** [comment]
For starters, we no longer store `S1.old` and `S2.old` on phase, but on the algorithm itself. We could do the same thing with regards to `phase[quantity]`

**Comment by jgostick** [comment]
Labelling this as revisit.  The updating seems to be unavoidable without major changes to things, and we've learned to live with it.  Maybe if we do a V3 we can rethink it then.

**Comment by jgostick** [comment]
This issue has just moved the forefront, as outlined in the discussion of issue #1536

**Comment by jgostick** [comment]
We can't really fix this, and it has some up-sides, so I think we need to close it.
