### ISSUE TITLE
Remove OpenPNM-Examples repository

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1369]
Now that we've completely migrated all our examples to the main repo, I think it's better to entirely retire and remove OpenPNM-Examples.

**Comment by jgostick** [comment]
I hesitated deleting the repo because I didn't love having the examples in the main repo, but I guess it's working out alright now.  

In an ideal world, we would keep the examples separate and somehow automate the testing suite to run both the openpnm and openpnm-examples on each push, and to fail if the examples didn't build...but that is pretty complicated to do I think.

**Comment by fablion** [comment]
At least, I suggest to change the link of the "Examples" tab on the main website. It is linked to the openpnm-examples directory.

**Comment by jgostick** [comment]
Done and done.  OpenPNM-Examples is now a private repo
