### ISSUE TITLE
Better handling of iterative properties

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1393]
At the moment, the user needs to manually specify which properties are iterative. This is fine since we can't/shouldn't make any assumptions in this regard. But, once a property is declared as `iterative_prop` by the user, `OpenPNM` **should** look up the dependency hierarchy and set upstream properties as `iterative_prop` as well. A good example is conductance, which could potentially depend on iterative properties.

**Comment by jgostick** [comment]
Technically it's possible since we have the dependency tree now, so we could look up all the parent nodes of the tree and regenerate them  if needed.  

However, I don't quite understand the use case.  Consider:

   B
 /
A -- C -- D
 
A depends on B and C, C depends on D.

If A is iterative should we regenerate B, C and D?

If A is *not* iterative, but *B* is iterative, we should regenerate A and B, but what about C and D?

**Comment by ma-sadeghi** [comment]
> If A is iterative should we regenerate B, C and D?

I think only upstream should be regenerated, in this case only B, or maybe I missing something?

> If A is not iterative, but B is iterative, we should regenerate A and B, but what about C and D?

How can B be iterative when all its dependencies are not? Maybe other dependencies that are not proper OpenPNM dictionary keys? Like scalars that, for some reason, might get updated during iterations?

I think, ideally, we only want to declare iterativeness of the bottom-most properties. For example, instead of setting `diffusive_conductance` to iterative, we'd rather set, for example, `viscosity` to iterative, and the algorithm automatically "infers" the iterativeness of upstream properties. Does that make sense?

**Comment by jgostick** [comment]
My diagram was meant to show that B and C-D were both upstream.

Regarding B being iterative but A is not, I think this is what you're saying about conductance.  If viscosity is set to be iterative (because of changing temperature), then conductance should inherit this mode.  Which is what I mean by B is set to iterative (viscosity) but A is not (conductance).

**Comment by ma-sadeghi** [comment]
This is addressed in PR #1445.
