### ISSUE TITLE
PETSc scaling issue

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1448]
This is relevant to our conversation in PR #1441.

Basically, although our PETSc wrapper works fine in many-core clusters without breaking, we're still lacking the scaling that we hoped for. Currently, we get at best close to 2-3X speedup (depending on number of unknowns, solver type, and CPU architecture). 

I tested our PETSc wrapper on Compute Canada using a simple diffusion script with ~3.5M pores, and compared it with a demo script which solves the diffusion equation with a nonlinear source term on a 3D lattice possibly using finite-difference, and here is the result:
![petsc_scaling](https://user-images.githubusercontent.com/14086031/76877331-992d3700-6849-11ea-9c13-83fb8a0319f0.png)
I don't know what exactly is holding us back from a nice close-to-ideal scaling.

For reference, here are the two scripts that I used for the scaling test: [bratu3d.py](https://gist.github.com/ma-sadeghi/b0b73e579d0836afd633860cc526107c), [pnm_petsc.py](https://gist.github.com/ma-sadeghi/45044acdda2658d7f67f68e13fd4d5c1)

**Comment by ma-sadeghi** [comment]
![petsc_scaling](https://user-images.githubusercontent.com/14086031/77178127-0dabe400-6a9d-11ea-8332-6c8aeac6c0e3.png)

**Comment by avlmachado** [comment]
Hello everyone, I'd like to share that I've tested the petsc wrapper in a cluster and observed a similar scaling problem. Indeed, the observed speedup was a little slower, 1.77.

I think the comparison of openPNM with bratu3d code is not fair, because in the CFD code there is also a domain decomposition and probably this is the main reason why scaling is optimal. 
I think if we could decompose and distribute the network between cores before the solution, that would be the best of all worlds.

**Comment by ma-sadeghi** [comment]
@avlmachado Thanks for sharing your experience. Would you be interested in looking into this issue in more depth and see if you can come up with a solution? Maybe prototyping a solution for the simplest case: simple diffusion on a cubic network... I know it's a lot to ask, but if it's something that interests you, we'd appreciate it a ton!
