### ISSUE TITLE
cache_A and cache_b cause nonlinear models to behave strange!

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1503]
There's something strange going on with `cache_A` and `cache_b`. When they're `True`, nonlinear models that change the base value of `A` (i.e. without BCs or source terms) are not enforced, meaning that `A` and `b` don't get updated accordingly.

**Note**: @magnaou Check `NernstPlanck` algorithm as well, maybe turn off cache for it too.

**Comment by jgostick** [comment]
I'm going to confess that these caches were conceived when I was refactoring the transport algs from V1 to 2, and I probably didn't think them through completely.  Please consider a complete 'rethink' if necessary.  It'd be nice if the caches knew themselves if/when they could be regenerated, instead of the coder needing to do this within the algorithm.  I'm not exactly sure what that looks like, but just throwing that out there.

**Comment by ma-sadeghi** [comment]
@jgostick I agree, caching should be mostly a backend thing with minimal need for user intervention. I'm looking into it.

**Comment by jgostick** [comment]
By user, I actually mean developer.  Having to keep all these function interactions in your head while also creating a new algorithm is just too much.

**Comment by ma-sadeghi** [comment]
This is now addressed in #1511
