### ISSUE TITLE
Problem with 'throat.partition_coef.all' not being set as iterative_prop nor updating when regenerate_models is called manually

### ISSUE THREAD

**Issue by mkaguer** [PMEAL/OpenPNM#1526]
I am writing a model where the partition coefficient changes with concentration. So it's important that 'throat.partition_coef.all' updates as 'throat.diffusive_conductance' (based on multiphase_diffusion) depends on this property to know partition coefficient.

**Comment by ma-sadeghi** [comment]
This has do with our automatic dependency handling that currently doesn't work very well with multi-level properties, i.e. `pore.foo.bar`

**Comment by ma-sadeghi** [comment]
@mkaguer This is now fixed on `dev`. Could you please try and give me your feedback?

There's only one API change:

```python
mphase.set_binary_partition_coef(propname="throat.partition_coef", phases=[water, air], model=model, **kwargs)
```
is now:
```python
mphase.set_binary_partition_coef(phases=[water, air], model=model, **kwargs)
```

since `propname` is redundant as we enforce `throat.partition_coef` (actually you _can_  change this prefix by modifying `mphase.settings["partition_coef_prefix"], whose default value is `throat.partition_coef`)
