### ISSUE TITLE
Default pore diameter in Imported class should be "inscribed" rather than "extended" (?)

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1527]

**Comment by ma-sadeghi** [comment]
I talked to @Zohaib-Atiq this morning and he thinks "inscribed" diameter gives more realistic results (although he mentioned that it's material-dependent). @jgostick Is there a particular reason why "extended" is the default in `Imported` class?

**Comment by jgostick** [comment]
Inscribed is too small, but it has the advantage that it 'shouldn't' create negative throat lengths, while the extended one may.

**Comment by ma-sadeghi** [comment]
@jgostick I see, what about in terms of accuracy, e.g. permeability/diffusivity calculations?

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi @jgostick I just realised that we have specified `throat.equivalent_diameter` instead of `throat.inscribed_diameter`. So if I change `pore.extended_diameter` to `pore.inscribed_diameter` then network could have throats bigger than pores. In PoreSpy `throat.equivalent_diameter` is the most efficient one. So I suggest to change `pore.extended_diameter` to `pore.equivalent_diameter`. Otherwise we have to change both `pore` and `throat` diameters to `inscribed_diameter`.

**Comment by ma-sadeghi** [comment]
@Zohaib-Atiq Can you do a quick study on different combinations?

**Comment by ma-sadeghi** [comment]
I feel like there isn't a single recipe that is the best for all types of problems, maybe one is better for diffusion the other for flow, etc. Until we do some real tests, we can't tell. I'll mark this issue as v3+ for now.

**Comment by jgostick** [comment]
Use of spheres is problematic due to overlaps and such.  We've actually moved to cones and cylinders as the default conductance model on imported networks, so closing this.
