### ISSUE TITLE
Allow topological manipulations when phase is associated to network

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1554]

**Comment by jgostick** [comment]
Deletions are ok, but additions are a problem since you don't know what values to put into the pores and throats.  If ALL the properties are coming from models, that's fine, but any properties have been hand-written, they become nans.  

Basically, yes, it's totally possible...I only prevented it because I didn't have the time to figure out the best policy for adding stuff.

**Comment by ma-sadeghi** [comment]
I see your point. Maybe putting `nans` as the default policy? Especially now with the enhanced `GenericTransport`'s sanity check method that almost always locates the root cause of `nans` in A matrix and raises a very descriptive `Exception`.

**Comment by jgostick** [comment]
Ya, nans are the obvious choice, so running ``regenerate_models`` and then putting nans everywhere else should do it.  

There is also the issue of geometry associations though...many of the manipulations also stop if geometries are found. This is a bit more tricky.
