### ISSUE TITLE
[Question]: Is there a way to scale an imported network

### ISSUE THREAD

**Issue by hazardary** [PMEAL/OpenPNM#1565]
I have used porespy and SNOW to extract a pore network from images. However, the scale is not properly done when I use SNOW. For my large images, redo SNOW can take a long time. I couldn't find a function to rescale the imported pore network from old study. Is there a way to scale the network?

**Comment by jgostick** [comment]
I think you're asking if it's possible to recalculate all the pore scale geometry properties of the network because you neglected to put voxel_size into the snow algorithm, right?  It is technically possible to multiply each property on the network accordingly, like ``pn['pore.diameter'] = pn['pore.diameter']*1e-4`` but this would be error prone and slow.  I'm afraid your best bet is just re-run the extraction, sorry.  

It'd be an interesting feature though, to have a tool that scaled everything in one shot.

**Comment by hazardary** [comment]
Thanks for replying. Besides geometry change, also the coordinates of pores. But I guess that only is for plot. It's good to know there isn't a method for now.

**Comment by jgostick** [comment]
Yes, like I said it would be error prone to do it by hand since things would inevitably get missed.
