### ISSUE TITLE
[Bug]: <Assigning integer value to geo2['pore.diameter'] changes all values in pn['pore.diameter'] to that integer>

### ISSUE THREAD

**Issue by taylrcawte** [PMEAL/OpenPNM#1574]
**Describe the bug**
After a geometry is updated using op.geometry.Imported(net) and new boundary pores are added, when assigning attributes to the new boundary pores if the value is an integer it changes all values of that attribute to the integer. If a float is used no issue. Found in https://github.com/PMEAL/OpenPNM/blob/dev/examples/extractions/Managing%20Geometrical%20Properties%20of%20Imported%20Networks.ipynb (CELL 16) geo2['pore.diameter '] = 2.0 VS. geo2['pore.diameter '] = 2. (using 2 overwrites the network pore.diameter values) 

**To Reproduce**
Steps to reproduce the behavior, ideally a code snippet that only reproduces the bug:
```python
<
pn = op.network.Delaunay(shape=[1, 1, 0], num_points=100)
pn['pore.diameter'] = np.random.rand(pn.Np)
print(pn)

geo = op.geometry.Imported(network=pn)

print(geo)

op.topotools.extend(network=pn, pore_coords = [[1.2, 1.2, 0]], labels='new')

geo2 = op.geometry.GenericGeometry(network=pn, pores=pn.pores('new'))
geo2['pore.diameter'] = 0

print(geo2)

print(pn['pore.diameter'])>
```

**Expected behavior**
The final print command should print the pn['pore.diameter'] values but instead it prints a list of 0s the length of geo + geo2.

**Screenshots**
![image](https://user-images.githubusercontent.com/65000690/87260665-0ca22680-c481-11ea-9ca8-838b9584db63.png)
vs. 
![image](https://user-images.githubusercontent.com/65000690/87260707-2f343f80-c481-11ea-8597-0717d7c2e2e1.png)

**Additional context**

**Comment by jgostick** [comment]
Hi @taylrcawte...thanks very much for the report and easy to reproduce code snippet!

This bug is a bit more subtle that it seems.  

It's not that all the values on ``geo`` get over-written with 0's.  In fact, the values on ``geo`` remain untouched.  If you do ``'print(geo['pore.diameter'])`` you'll see the original correct values.

The problem is with the ``interleave_data`` function, which must decide which datatype to use when compiling the pore.diameter values from ``geo`` and ``geo2`` into a single array.  For what ever reason, it converts them to int, so the float values on ``geo`` get truncated, and *appear* as all zeros.  Had the values been > 1, you'd see non-zero values in there.  

This is certainly a bug, since the 'interleave' process seems to have made a mistake in choosing the datatype.  I would have expected it to always assume float when there is a conflict.  I will push a fix asap.

**Comment by taylrcawte** [comment]
Awesome! 

Thank you!

**Comment by jgostick** [comment]
It's still a bug...the type conversion is not working properly.
