### ISSUE TITLE
[Feature Request]: continuity boundary condition between networks

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1579]
**Is your feature request related to a problem? Please describe.**
When modeling a multidomain problem, such as in fuel cells where we have GDL and CL, it's not trivial to connect GDL-CL interface pores. In fact, the pore connectivity at interface is not important, but rather the mass distribution between the two domains is.

**Describe the solution you'd like**
No need to stitch the two networks, instead have a method like `set_continuity` that satisfies the mass distribution requirement through adding a virtual interface pore and taking care of matrix assembly, etc.

**Comment by TomTranter** [comment]
Sounds useful. Did you make any progress on this?

**Comment by ma-sadeghi** [comment]
Not really. I'm wondering if this can be done without adding a fictitious pore (to preserve Np by Np structure).

**Comment by jgostick** [comment]
Firstly, I'm not sure that a single 'joint pore' is a good idea since it loses the 'heterogeneity' of the pore network.  It's probably better to keep the pore-to-pore connections.  
 
I have added a function that accomplished the 'automatic' stitching of pores between a pore network and a continuum region.  The function is called [merge pores](https://github.com/PMEAL/OpenPNM/blob/743707ddcf56c4e229c95ff528210eae3b42ea73/openpnm/topotools/topotools.py#L827)
