### ISSUE TITLE
[Question]: Net flow rate is not zero for permeability calculation

### ISSUE THREAD

**Issue by hazardary** [PMEAL/OpenPNM#1633]
I am implementing permeability calculation for a extracted network with both water phase and air phase in the network. I have been study the code in OpenPNM/examples/simulations/Relative Permeability in 2D.ipynb. In the last snippet of code I found that flow rate of the boundary where pressure is assigned to 1, is used to calculate permeability. In my code I used flow rate from the outlet. But it shouldn't matter because the net flow rate should be zero and the inlet flow rate should be equal to outlet flow rate. So I check the net flow rate in this example by simply print out the flow rates.
They are same in the case where no air is in the network (Input 5 and 6)
![image](https://user-images.githubusercontent.com/20841062/91646685-ce0bff80-ea1f-11ea-9135-ce7fea2aace8.png)
However, they are not same when percolation result is introduced (Input 7 an 8)
![image](https://user-images.githubusercontent.com/20841062/91646703-14615e80-ea20-11ea-9c70-6019457cf7dc.png)
How do you explain this?

My second question is: in the example, pressure boundary condition are set for inlet and outlet. Conditions on the other boundaries are not set explicitly. From the above picture you can see that the flow rate are small compared to the inlet and outlet flow rates but not zero. Even if I set those two boundaries to have 0 rate can't make the flow rate absolutely zero.

**Comment by jgostick** [comment]
To answer your second question first, when you do 'left' and 'right', you probably also get some 'top' and bottom' pores.  Though you said you were working on an extracted network, so maybe my answer is not correct.  Check to see if pn.pores('left') and pn.pores('front') have any pore indices in common.

Regarding your first point, the only way that the inlet and outlet would not match is if the solution did not converge.  If you are injecting into the same face as you apply the pressure bc, then it's possible that you're hydraulic conductivities are all vanishingly small (since the throats are filled with non-flowing phase), so this would wreak havoc on your simulation.  Also, we fixed a bug a few months ago regarding the 'reuse' of algorithm objects, so be sure that you're using the latest openpnm version (now 2.5.0)

**Comment by jgostick** [comment]
Since I haven't heard back from you, I'm going to assume this problem is solved and close this issue.  Feel free to re-open if needed.
