### ISSUE TITLE
Problem with network extraction examples

### ISSUE THREAD

**Issue by Ni2M** [PMEAL/OpenPNM#1646]
For some reason the example for the Berea simulation gives 1 additional pore in its network extraction, while the resulting network  from test runs have 1 less pore. Accordingly, the results for simulations will be different as well. I'm checking the versions of the libraries and PoreSpy first.

**Comment by ma-sadeghi** [comment]
@Ni2M Actually, I experienced the same issue in a recent PR, and it turned out that it's Linux/Windows issue. For some reason, on Linux, we sometimes get slightly different results, which is OK. Since the CI machine that runs our examples runs Linux, and incidentally most of us are using Windows, occasionally we have this issue.

Long story short, this is not a bug on our side, but an OS-dependent issue, which is out of our hands. So, no need to worry about it.

**Comment by Ni2M** [comment]
Thank you @ma-sadeghi for your explanations. That is true. I also found a similar reasoning on my search on the internet for some other software. There was the possibility to run CI locally to see if the results are the same or not, but the OS are still different. Thank you.

**Comment by jgostick** [comment]
So the solution is the #NB_VAL INGORE the offending cells?

**Comment by ma-sadeghi** [comment]
@jgostick I'd suggest to leave it as is. If I remember correctly, the Berea example is the only one having this OS-dependent problem. So, as long as we're not changing the example, it should be fine. Btw, I already updated the Berea example on dev using a native Linux installation, so the test is passing on dev.

**Comment by jgostick** [comment]
I had to change the example since the 'name' of the object now appears in the settings dict, so upon re-running it I broke the ubuntu tests.  I have added the ignore and a message to future selves about why.
