### ISSUE TITLE
Add outflow_BC to PNP

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#1657]

**Comment by magnaou** [comment]
I just checked the code. Apparently, it needs more work than what I thought. We can't inherit directly from the "AdvectionDiffusion" class to get the "set_outflow_BC" because the migration term is missing there! So, I'm deriving and making a new "ish" BC to work with the "NersntPlanck" class. Stay tuned @mkaguer

**Comment by mkaguer** [comment]
Ok, great thanks @magnaou

**Comment by mkaguer** [comment]
Oh and @magnaou one other thing. The _apply_BC method will need to be updated for the nernst planck algorithm as well so that it looks for set_outflow_BC. The AdvectionDiffusion class does this. Maybe you already noticed this but I wanted to bring it to your attention in case not.

**Comment by magnaou** [comment]
Fixed on PR #1667

**Comment by magnaou** [comment]
Yes @mkaguer thanks for reporting that. I need to debug it again. I had it working before merging dev into it again.
