### ISSUE TITLE
Why do we need both Generic and ReactiveTransport?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1662]
Currently, `ReactiveTransport` is `GenericTransport` with the ability to add source terms. However, I feel like a "generic" transport class is not generic if it doesn't natively support source terms, hence maybe they should be one? Any thoughts?

**Comment by jgostick** [comment]
There is not really a reason except division of code.  I read an article on the birth of oop (simula 67), and the author points out that one of the benefits of oop is that it's actually much easier for a programmer to learn the code, since they can tackle it in chunks.  So first they learn GenericTransport to see how the A matrix is built and how BCs are applied, then they can study ReactiveTransport to see about the linearization of source terms and the iterative scheme, and so on. It's also easier to maintain smaller files, where tasks and roles are compartmentalized.  Basically, it's practical rather than necessity.  I'm going to close this since I think we should keep them separate.
