### ISSUE TITLE
How to handle extra boundary pores added by SNOW extraction method from porespy? 

### ISSUE THREAD

**Issue by taylrcawte** [PMEAL/OpenPNM#1668]
**Background**
I have been generating and extracting networks with porespy and performing analyses in openpnm. Until recently I did not realize that if the "boundary_faces"  parameter is left blank in the SNOW algorithm, the algorithm would automatically add boundary pores to *_all_* faces. It appears to me that these boundary pores are labelled as "top", "bottom", "front" etc. After extracting the network in porespy i added additional boundary pores in openpnm using the add_boundary_pore function.  Initially i did not think that having 2 sets of boundary pores would impact any transport simulations due to the fact that neither of the boundary pore sets *_should_* have volume, however, upon further inspection i found that the boundary pores generated during extraction do have volume, and running the simulations using the 2nd boundary pore as the inlet yields different results than the simulations with the porespy added boundary pores as inlets! 

**Question**
Are the boundary pores added by porespy in the SNOW algorithm actual boundary pores or are the part of the original network? do i need to manually set their properties (i.e. set their volume to 0)? Should i do a manual watershed extraction to avoid the extra boundary pores being added?  

**Code**
Below is the entire code i used to generate a network, run ordinary percolation, and calculate the relative diffusivity and permeability. 

[sample_code.py](https://gist.github.com/ma-sadeghi/e85a7fdac3a9ecc6afb0300988517e0c)

**Comment by ma-sadeghi** [comment]
@taylrcawte I edited your question and created a Github gist instead for readability.

**Comment by ma-sadeghi** [comment]
@taylrcawte We've been meaning to properly deal with boundary pores in OpenPNM but we haven't found the time yet.

Boundary pores in the SNOW algorithm are not part of the original image, and need to be treated differently. I think SNOW already puts in reasonable values so you can directly import them in OpenPNM without any further modifications. @Zohaib-Atiq is that right?

**Comment by Zohaib-Atiq** [comment]
@taylrcawte 
Instead `net = psp.networks.snow(im=im, voxel_size=1e-6)`
Use `net = psp.networks.snow(im=im, voxel_size=1e-6, boundary_faces=None)` This will not extract boundary pores for you.

SNOW gives you real pores with certain value of volume. This is needed in transient simulation. If you don't want that volume some how in your simulation you can put a zero value for these pores manually.

**Comment by taylrcawte** [comment]
@Zohaib-Atiq Do you know if the labels will still be applied to surface pores? im currently using the labelled pores as a way to add my boundary pores easily afterwards... Also how do you ensure that the boundary pores don't impact transport calculations if they have a non zero volume?

**Comment by ma-sadeghi** [comment]
> @Zohaib-Atiq Do you know if the labels will still be applied to surface pores? im currently using the labelled pores as a way to add my boundary pores easily afterwards... Also how do you ensure that the boundary pores don't impact transport calculations if they have a non zero volume?

I'll give my two cents: regarding your first question, I don't think so, but you can do it yourself using a workaround: basically, use SNOW with labels, and then use `OpenPNM` to relabel the pores by looking up the neighbor pores to each label.
```python
actual_left = net.find_neighbor_pores(pores=net.pores("left"), mode="xor")
op.topotools.trim(pores=net.pores("left"))
net.set_label("left", pores=actual_left)
```
Regarding your second question, zero volume makes sense, but it screws up conductance calculations as a pore with zero diameter imposes infinite resistance, at least based on how we define conductance models in `OpenPNM`. If you manually set pore length to a small number, effectively you get a high conductance for boundary pores, but I'm not exactly sure if `porespy` currently does this.

Anyway, like I said earlier, boundary pores are not exactly properly dealt with at the moment and we're going to address them in near future (hopefully!).

**Comment by ma-sadeghi** [comment]
@taylrcawte Btw, did a bunch of numerical experiments the other day and it turned out that for relatively small networks (my made-up rule of thumb: less than 10 pores across each dimension), using SNOW boundary pores gives significantly different results compared to when using the approach I briefly explained above, maybe up to 50% difference between the two. However, for large enough networks (again, my made-up rule of thumb: more than 50-100 pores across each dimension), it doesn't make much difference.

As to which of the two approaches are more correct, the approach explained above is clearly wrong, since it misses the resistance due to half of the boundary pores (internal, but used as boundary condition). So, we definitely need to add some sort of boundary pores that themselves don't contribute (or contribute very slightly) to the overall conductance. Whether or not our current SNOW boundary pores are suitable is currently a mystery!

Anyway, properly dealing with boundary pores (and possibly fixing SNOW boundary pores in case something's wrong with them) is our next top priority mini project. So, stay tuned. Hopefully, we'll take care of this by the of October or more likely December.

I'm closing this thread, but will reference it in another issue (#1425) where we will discuss how to move forward regarding this. Feel free to chime in and let us know if you have any ideas, etc.

**Comment by taylrcawte** [comment]
Thanks @ma-sadeghi i'm currently running some validation on the networks i'm using and will jump into #1425 when i have some answers!
