### ISSUE TITLE
Specialize Exceptions

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1670]
While it's considered best practice to use Python's default Exceptions if possible, I think adding a few of our own might be worth it. I propose adding the following Exceptions:

- `SolverError` -> `NotConvergedError`
- `MissingDependencyError`
- `NetworkTopologyError`

**Comment by jgostick** [comment]
Great point...I'd been pondering this recently too.

**Comment by jgostick** [comment]
https://docs.python.org/3/library/exceptions.html#exception-hierarchy

**Comment by jgostick** [comment]
I'm actually questioning the wisdom of this.  At the moment we print a descriptive message with each exception, and the python trace back is very detailed.  I am not sure that adding specialized exceptions will make things any more clear, but I am sure that they will be a huge pain in the butt to code, since you have to try/accept based on the expected exception, so this will add a lot of uncertainty to the mix.

**Comment by jgostick** [comment]
@ma-sadeghi posted a talk to the teams channel a few weeks ago, in which the author said that subclassing exceptions was terrible idea since it led to class creep.  I'm inclinded to agree.  We should stick to the available exceptions, and just add useful messages.
