### ISSUE TITLE
Percolation algorithm

### ISSUE THREAD

**Issue by saeidabd** [PMEAL/OpenPNM#1721]
Dear @jgostick jgostick
I am working with your ready-made framework, OpenPNM, trying to simulate some invasion processes. I need help to handle the percolation algorithm in:

1- Invasion of oil in a water saturated pore network with oil ( under water-wet condition, meaning drainage)

2- At the end of the drainage once the phase saturations are known, I'd like to change the contact angle to an oil-wet condition (simulating the aging process).    

3- Imbibition of water to the pore network.  

The main problem is in the second step, when I need to model the aging process. When I change water pore contact angle in every value I want, the pore invasion sequence will not change and the capillary curve just shifts upward or downward (vertically) while we know this is not true in experimental tests and the pore sequence depends on contact angle.
Is it possible to simulate these steps in OpenPNM (especially, step2)? If yes, how?

**Comment by jgostick** [comment]
If you just change contact angle uniformly in every throat, theoretically nothing will change except the shift up or down.  This is dictated by the Washburn equation.  However, there are lots of extra things to consider.  If you change the contact angle according to some distribution, then things will change.  If your angles change a lot (50 to 150) then wettability will change, but this is much more difficult to model.  If the angles are near 90 then the meniscii can balloon and touch each other of the back of pores.  We have considered this in a recent paper and it's implemented in openpnm, but again, its quite complicated.  

Imbibition is also complicated because there are many mechanisms at work, unlike drainage which is basically just one.  We have the MixedPercolation class which can do imbibition and there is an example in the examples folder.

https://github.com/PMEAL/OpenPNM/tree/dev/examples/notebooks/algorithms/percolation

Read through these examples, and then get back to me if you still have problems.
