### ISSUE TITLE
2d and 3d versions of electroneutrality, Poisson, and Laplace models are identical

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1753]
I think we should get rid of the 2d versions.

**Comment by ma-sadeghi** [comment]
This is approved.

**Comment by jgostick** [comment]
Maybe let's wait until v3.0?  This is not urgent.

**Comment by jgostick** [comment]
We closed this PR because 2D and 3D are now declared in the size_coefficient models, so this should trickle down to all other models without them having to think about it.  Meaning, the hydraulic and diffusive conductance models use the 'size_coefficient' without needing to know 2D vs 3D, and the the ad_diff and ad_diff_mig models use the hydraulic and diffusive conductance models.

**Comment by Ni2M** [comment]
After we discussed, we now will change the code so that the 2D models are removed and the inputs for the ionic cond and source term models are accepting diffusive conductance (not conduit length, etc). No need for net.dim checking. I'll open a new PR related.
