### ISSUE TITLE
Fully-connected validation in GenericTransport fails for bundle of tubes

### ISSUE THREAD

**Issue by xu-kai-xu** [PMEAL/OpenPNM#1783]
**Is your feature request related to a problem? Please describe.**
Hi, I just upgrade to the version 2.5.1, and found that there is a `fully-connected validation` in the `GenericTransport` class, as a default-included option. But i am intending to make a PNM not fully connected. This default setting seems inappropriate in this situation.

**Describe the solution you'd like**
I suggest that you may exclude the fully-connected validation from the default options by setting the \*\*kwarg as `False`. 

**Describe alternatives you've considered**
I understand that in most cases, PNM is set as fully-connected, which is the reason you add this check code. I can just comment the code scripts for my convenience. You may decide whether or not to apply this revision suggestion.

Thanks.!

**Comment by ma-sadeghi** [comment]
Hi @xu-kai-xu, that check is necessary since disconnected networks result in indeterminate `A` matrices. Please let me know if I'm missing something.

**Comment by xu-kai-xu** [comment]
for example, I want to make a unidirectional PNM, as follows:
![image](https://user-images.githubusercontent.com/44153643/99971171-c9b17180-2dd7-11eb-9b7e-4ec46013a1ef.png)
It is not fully connected, but partly-connected.
When I use version 2.1, I can calculate permeability.

Then When I use version 2.5.1, It raises an exception 
'''
 "Your network is clustered. Run h = net.check_network_health()"
" followed by op.topotools.trim(net, pores=h['trim_pores'])"
 " to make your network fully connected."
'''

I think partially-connected is ok, in this case.

**Comment by jgostick** [comment]
@xu-kai-xu makes a good point actually. You can do a bundle of tubes model as well, even though they are 'clustered'.  I think the way boundary conditions are applied might somehow 'connect' the other disconnected channels? Because it does solve.  We should think about this, and identify a more subtle way to check for the health of the A matrix.

**Comment by xu-kai-xu** [comment]
Yes, the boundary condition plays an important role in this case. If boundary condition changes, there may be no solution.

**Comment by ma-sadeghi** [comment]
@xu-kai-xu You're right, I didn't think of that scenario.

Actually, now that I think about it, I can't think of what could possibly go wrong if a network is clustered, since we already set x0 = 0, if no BC is found, x0 = 0 is propagated across the entire network (or that BC-less specific cluster).

I just tested it and it works! So, maybe we can entirely get rid of that part? @jgostick 

Maybe I'm oversimplifying it though.

**Comment by jgostick** [comment]
The check should actually make sure that all pores are connected to the boundary pores.  I think this will requiring adding a fictional pore that connects all the boundary pores together,  THEN run clustering and count numbers.  Note that AdDiff may require a special approach.

**Comment by jgostick** [comment]
Actually, I think this may be impossible to fix.  We'd need to know which pores are considered inlets and which are considered outlets. At present all the BCs are just in a big lumped pot and there is not way to know.  I can write a method that gets some of the cases (like will pass for bundle of tubes), but cannot catch all the cases (i.e may return false True when should be False).

**Comment by jgostick** [comment]
never mind...I read comment above and realized how to do it.  Fix is pushed.
