### ISSUE TITLE
alg.settings['sources'] should be a set, not a list

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1951]
We want `alg.settings['sources']` to be unique, so why not change its data type to `set`? This gets rid of some manual checks we do here and there, for instance:

https://github.com/PMEAL/OpenPNM/blob/bdb1daac683aa1192ad5f826c0d644395e0adde6/openpnm/algorithms/ReactiveTransport.py#L219-L220

Clearly, not urgent at all, just a note for future.

**Comment by jgostick** [comment]
Sets are immutable.  Once you create it you can't add more do it.  It does not have an ``append `` attr for instance.  The only solution, to simplify the checks, is to do ``list(set(a))`` which converts it to a set to remove dupes, then back to a list.  

Also, it's not possible to force the setting to contain a list, so it's better to adapt on the fly using ``list(set(a))``.

So, this issue's focus has now pivoted.  Instead of trying to make the setting be a list, search through the code for any places that this setting is being used and replace any checks for uniqueness with ``list(set(a)`` where ``a = self.settings['sources']``

**Comment by ma-sadeghi** [comment]
@jgostick I think you can add/remove items to/from a set using `x.add`/`x.remove`.
