### ISSUE TITLE
Allow passing scalar values as argument to built-in source term models

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#1956]
Something like:
```python
mod = op.models.physics.generic_source_term.standard_kinetics
k, n = 1e-4, 2
phys.add_model(
    X="pore.concentration",
    propname="pore.rxn",
    model=mod, prefactor=k, exponent=n,
    regen_mode="deferred"
)
```

**Comment by jgostick** [comment]
The only way to do this is on a case-by-case basis.  You can easily accept scalars into a function, but ONLY if the function is expecting them.  If the function is expecting a dict key, like ``self[prefactor]``, then this will work if ``prefactor='pore.k'`` and fail if ``prefactor=1.0``.  

I cannot think of a universal way to handle both without the function author planning for it.  It *might* be possible to change the ``__getitem__`` method of ``Base`` so that if the ``key`` argument is a numerical value then it just returns that value, like:

``` python

def __getitem__(self, key):
    if isnumeric(key):
        return key
    else:
        ...
```

But this seems pretty sketchy to me.  Far too much magic.

**Comment by jgostick** [comment]
I'm actually starting to like this idea!  I recently saw a precedent for it in pandas.  You can do ``df['key']`` and get a whole column, or ``df[:10]`` to get the first 10 rows of all columns.  So it's not totally off-base to interpret the key differently.  

I'm going to tag this with the Refactor Base milestone, and implement it, then we can see how we like it, maybe remove it later.
