### ISSUE TITLE
Store original shape and spacing of all networks in settings

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2059]

**Comment by jgostick** [comment]
My aim was to actually **remove** functions from the network classes.  The problem is that the functions don't always work, for instance if boundary pores were added, or a two cubics were stitched together.  Having them as methods implied that they should always just work, while having them as functions lets us point out to the user that the network must be truly cubic.  

Also, I didn't like that each network class had different methods.  I wanted them to be more consistent and (in principle) easier to work with.

**Comment by ma-sadeghi** [comment]
I see, how about storing shape and spacing as **static** underscore properties, just for reference (it's handy to check the shape of the network using net._shape).

**Comment by jgostick** [comment]
I might conceed to putting them in the settings upon initialization, some like ``pn.settings['orig_shape']``
