### ISSUE TITLE
Project's find_phase doesn't work with algorithms

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2213]
```python
net = op.network.Cubic(shape=[1,2,3], name="bob")
air = op.phases.Air(network=net)
fd = op.algorithms.FickianDiffusion(network=net, phase=air)
print(net.project.find_phase(fd))
```
```python
runfile('/home/amin/Code/scripts/temp.py', wdir='/home/amin/Code/scripts')
Traceback (most recent call last):

  File "/home/amin/Code/scripts/temp.py", line 53, in <module>
    print(net.project.find_phase(fd))

  File "/home/amin/Code/OpenPNM/openpnm/utils/_project.py", line 249, in find_phase
    raise Exception('Cannot find a phase associated with '+obj.name)

Exception: Cannot find a phase associated with fick_01
```

**Comment by ma-sadeghi** [comment]
@jgostick Could you please take a look?

**Comment by jgostick** [comment]
Add the following the ``find_phase`` method on the project:

```
        if obj._isa('algorithm'):
            return self[obj.settings.phase]
```

**Comment by jgostick** [comment]
Actually, on second thought, I think we should change the code in the algorithm. If you want the phase you should just do: ``phase = self.project[self.settings.phase]``.  The reason is that an algorithm might have more than 1 phase, and each algorithm should just look up as needed.  Maybe it should be ``wp, nwp = [self.project[p] for p in self.settings.phases]`` for instance.

**Comment by ma-sadeghi** [comment]
Agreed, just pushed a fix directly to dev.

**Comment by ma-sadeghi** [comment]
For reference, I added an exception when an `algorithm` is received by `Project.find_phase` to avoid confusion.
