### ISSUE TITLE
Invasion Percolation issue

### ISSUE THREAD

**Issue by debanik1** [PMEAL/OpenPNM#2232]
I get the following error while implementing [Invasion Percolation (IP)](https://github.com/PMEAL/OpenPNM/blob/dev/examples/notebooks/algorithms/percolation/B_invasion_percolation.ipynb) algorithm.

"AttributeError: module 'openpnm.topotools' has no attribute 'generate_voxel_image'"

**Comment by jgostick** [comment]
Hmmm.  This has something to do with your openpnm version.  How did you install openpnm?

**Comment by debanik1** [comment]
In the beginning, porespy was missing. Then I upgraded using 'pip install porespy'. I tried to run the IP algorithm and got the error message. I realised that some modules are missing even after updating. What do you suggest? May be uninstall and reinstall? Is there a link which takes through step by step installation of the latest version?

**Comment by jgostick** [comment]
Ok, I see the problem.  We are in the middle of converting to V3, and the docs on the website are in a bit of flux.  We've removed the ``generate_voxel_image`` from porespy and put in on openpnm.  But it's only the "dev" version of openpnm at the moment.  Installing the dev version is a bit complicated but not impossible.  There are instructions [here](https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/using_and_contributing_to_the_dev_version.md)

**Comment by jgostick** [comment]
Once you have the dev version of openpnm installed, you can 'checkout' the dev branch and you'll have access to the missing function, BUT....other examples will break!  Due to the large amount of changes, we decided to stop making sure all the examples passed, and we plan to update them later.  

I just occurred to me, there is a better solution.  You should look at a old version of the example:  https://github.com/PMEAL/OpenPNM/tree/release/examples/notebooks/algorithms/percolation.  Let me know if this works.

**Comment by debanik1** [comment]
> Once you have the dev version of openpnm installed, you can 'checkout' the dev branch and you'll have access to the missing function, BUT....other examples will break! Due to the large amount of changes, we decided to stop making sure all the examples passed, and we plan to update them later.
> 
> I just occurred to me, there is a better solution. You should look at a old version of the example: https://github.com/PMEAL/OpenPNM/tree/release/examples/notebooks/algorithms/percolation. Let me know if this works.

This link works for now.
