### ISSUE TITLE
Should import functions continue to return a project or just a network?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#2412]
The io functions would return a project since the ``Network`` and the ``Geometry`` would be created, so a project made sense.  However, now it's all just on the ``Network`` so returning a project is a bit redundant.  However, it's not totally unheard of for functions to returns lists which you must index into, like ``np.where`` or ``scipy.ndimage.label``.  So maybe ``net = op.io.from_blah(<filename>)[0]`` is not that bad.  

Not sure which way I lean here.

**Comment by ma-sadeghi** [comment]
I'd say let's just return the network object. `np.where` indeed returns a tuple that needs to be indexed using `[0]`, however, that's when you only pass a single argument. If you pass `np.where(x, y, z)`, it returns a numpy array whose elements are chosen from `y` or `z` based on the condition `x`. My point is, since `io` classes don't have multiple signatures, returning a list that needs to be indexed seems redundant.
