### ISSUE TITLE
Distribution of defending_phase in Invasion Percolation

### ISSUE THREAD

**Issue by upceric** [PMEAL/OpenPNM#251]
In the invasion-percolation process, can I choose some pores or throats filled with invading_phase before the IP?

**Comment by jgostick** [comment]
I've assigned this to @HaroldDay since he is working on the new fancy IP algorithm...this is one of the features that it should have.

**Comment by upceric** [comment]
It is great to see any improvement in this project.

**Comment by jhinebau** [comment]
I have two requests for Harold:
1: treat pores and throats identically (calc Pc for each and invade lowest Pc at each step). This will allow for the algorithm to be imbibition/drainage ambiguous.
2: allow for Pc to be updated on each step. This will allow the work that Mostafa, Hang, and I are working on to fit into your alg. We're doing some viscous/gravity fanciness.

**Comment by jgostick** [comment]
Yes, I have actually PR'd my recent work called IP2, which allows you to
specify how many steps to invade, rather than doing a all at once.  The
point of this is to allow entry pressure to be recalculated as detached
clusters form with different static pressure heads.  Also, there is a model
called static_pressure in the physics.models.capillary_pressure file.

**Comment by jgostick** [comment]
This feature (i.e. distribution of residual phase in IP) is/will be part of the AwesomeIP PR ( #421)
