### ISSUE TITLE
Default mode for `set_value_BC` throws unnecessary Exception

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#2515]
When running a script twice (or just running that specific line where the BCs are being applied twice), `OpenPNM` complains that some of the pores already have some BCs assigned.

**Comment by jgostick** [comment]
The default behavior is `add`, and the exception clearly says use `overwrite` if any bcs are already present.  So, the 'power user' can just specify `mode='overwrite'` in their cells if they want to reuse the alg, otherwise a helpful error message is issued.  I think we should keep the default behavior as `add` since this is more safe for most cases.
