### ISSUE TITLE
Particle fluid simulation

### ISSUE THREAD

**Issue by domist07** [PMEAL/OpenPNM#2668]
I have a group of particles (blue and green lines in the image) flowing through a porous body. Is there a way to simulate and record the paths of the particles? In particular, I am interested in places (edges or nodes) where the particles interfere with each other due to constrictions, or where blockages are threatening (in red circle).

![OpenPNM_Feature-Request](https://user-images.githubusercontent.com/59735059/211565802-dfebca5e-d0e9-4d21-8a0b-063be6d26c26.png)

**Comment by jgostick** [comment]
There are probably lots of ways to do this, since studying streamlines on meshes has been a CFD subject for a long time, but I always look for 'pixel/voxel' ways since those are the tools I know best.  If you could convert the stream lines into a voxel image, with 1's indicing paths, and 0's elsewhere, then you could do some image analysis.  For instance, you could dilate the lines so that nearby lines merge, then could the number of lines you have left. You could analyze the pseudo skeleton that you've just created to find junctions, which would be places where the streamlines touch.  You'd could see that on a given cluster of voxels, it has X starting points on the inlet face, which all merge into Y constrictions, then branch back out to Z end points.  You could do a 'diffusion' simulation on the skeleton to find 'hot spots' where the local transport is high.  

It all depend on what you mean by "interested in places".  Whatever the case, I don't think this is a feature we'll be putting into OpenPNM/PoreSpy, more like a use case of the code we already have, so I'm going to transfer it to the Discussion section.
