### ISSUE TITLE
io options are not working

### ISSUE THREAD

**Issue by himanshu-jain-in** [PMEAL/OpenPNM#2678]
![image](https://user-images.githubusercontent.com/91551982/215251779-3c9dc4ce-f2c8-47f4-abb5-f3f6e5ea2a33.png)

Tried installing the package several times but still, the function is not working. Also not available on GitHub.

**Comment by jgostick** [comment]
This 'probably' means you are installing version 2 of openpnm but running a script designed for version 3.  What happens when you type ``op.__version__`` at the command line?

**Comment by himanshu-jain-in** [comment]
'2.6.1'
How to update openpnm?

**Comment by jgostick** [comment]
The easiest way to is to create a new virtual environment.  Updating packages can be a real pain due to dependency conflicts.  You **could** try with ``conda install -c conda-forge openpnm>3`` (double check the conda docs for how to specify version numbers).  But probably better to do:
``conda create -n new_env python=3.9`` (or whatever name you like)
``conda install -c conda-forge openpnm``
