### ISSUE TITLE
Make geom and phys __getitem__ look into net and phase?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#295]
At the moment, geom['pore.diameter'] returns data, and net['pore.diameter'] looks into geom and returns the same data.  

Might it also be a good idea if it worked the other way too?  So geom['pore.coords'] look into itself, finds nothing, then looks into net, finds net['pore.coords'] and returns the 'pore.coord' values corresponding to each pore in the geom?

**Comment by TomTranter** [comment]
Yes, it would be really useful to be able to do geom['throat.conns'] too. I must have coded 3 or 4 different versions of this lookup throughout developing Voronoi and it's still not straight-forward with the new mapping. Although maybe we should try to limit the data we store directly on the network instead.

**Comment by jgostick** [comment]
Make sure that geom['throat.conns'] returns a list of pore indices in the Geometry numbering, not the network numbering.

**Comment by jgostick** [comment]
Ok, got this working and have updated the PR...BUT there is a glitch.  The pore numbers stored in conns are ints, but we can't insert nan's into an int array.  I can either convert the list to floats, or use -1's instead of nan.  Thoughts?

**Comment by TomTranter** [comment]
Turning it into float is bad for indexing and -1 is also likely to cause problems with indexes. Either way another step is needed to manipulate the data to remove those throats from whatever you're doing. If the situation only happens when a throat in the geometry connects a pore not in the geometry maybe the index of the pore found should be returned in both positions. Or maybe it should never happen and we enforce/suggest as good practice throats connecting different geometries to be placed in a special interface geometry type and then we could subclass the getitem for this particular geometry slightly differently. Another solution would be to return the network indices and print a warning when the conversion can't be done neatly. I think I like interfaces the best,

**Comment by jgostick** [comment]
Firstly, the PR doesn't work after all, but I'll get that straight shortly
Second, -1 is absolutely out, since this will not throw an error, but actually index to the last element of an array.

**Comment by jgostick** [comment]
Bug fixed...this now returns -1's for pores not found.

**Comment by jgostick** [comment]
A 4th option is to return a Numpy of array of type 'object' which DOES allows ints and nans in the same array.  It is slower to use when indexing, but this would see very limited use so may be ok?

**Comment by jgostick** [comment]
I just pushed nice version, that only returns an object dtype if there are nans, and returns the regular int dtype otherwise.  I think we should merge this.  Play with it and let me know.

**Comment by jgostick** [comment]
This is now done, Geom lookup Network data and Physics can look up Phase data.  There was an additional thought, however, about should Geom be able to look up Physics data?  They are 'next to each other' in a conceptual stack of object layers, so it might make sense for these layers to 'talk' to each other.  It turns out this is not possible.   If there are more than 1 Phase, the Geometry cannot get a single answer when querying Physics, hence consistency and symmetry are not possible...there it's a no-go.
