### ISSUE TITLE
fix doc_test in Core._interleave_data

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#358]
The last line of the doc test checks the returned data type and expects an int32, but this is machine dependent, so my machine returns an int64.  The test should be fixed, but perhaps Travis should be configured to do 32 and 64 bit builds?

**Comment by bspellio** [comment]
This doesn't have to do with the system, the numbers in int32 and int64 refer to the number of bits allocated to each integer. Since a bit can be either 1 or 0, int32 can represent the range of  (-2147483648 to 2147483647) while int64 can represent the range of (-9223372036854775808 to 9223372036854775807). See the NumPy docs here: http://docs.scipy.org/doc/numpy/user/basics.types.html

**Comment by jgostick** [comment]
It has something to do with the type of Python install you have, or perhaps the Scipy/Numpy install.  if you ask for dtype=int sometimes you get int64, sometime int32.
