### ISSUE TITLE
Proper Brevais Lattices

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#505]
The DelaunayCubic class is great, but needs to be renamed to BravaisLattice.  This is the general term for any cubic packing and there is well-defined notation for the lattice structure which should be given as the arguments.  [See Wikipedia](https://en.wikipedia.org/wiki/Bravais_lattice).

Basically, we need to produce some system of arguments that can reproduce all the arrangements there.  I love the idea of skewed networks too!

**Comment by TomTranter** [comment]
I like this idea. Also with actual structures it is more likely that the lattice points are solid particles or agglomerates rather than pores. It would be cool if you could produce a network treating points as either solid or void. I think this would more or less entail swapping the pore coordinates with the vertices of a Voronoi diagram.

**Comment by jgostick** [comment]
I'd like to make this one of the key new features of V1.5.

**Comment by jgostick** [comment]
This is probably not a good thing to spend time on.  There is already the DelaunayCubic with does this sort of by specifying 'bcc' or 'fcc'.  I think that class should be renamed to be more descriptive, but that means breaking things.  Let's close this for now and revisit if and when it makes sense.
