### ISSUE TITLE
Add an Interface class?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#581]
There are are properties that only exist at interfaces between phases, such as surface tension, surface area, curvature, etc.  It would not be too tricky to do, and I actually mocked up a class in a side project that worked something like:

```
aw_int = op.Phases.Interface(network=pn, phase1=air, phase2=water)
aw_int['throat.surface_tension']  = 0.072

```

It's something to think about, but I'm guess that nobody really needs it right now so we don't really know what we need.

**Comment by stadelmanma** [comment]
A class like this could be used to add flexibility to the model I am working on and I love the rigidity defining interface properties separately adds. Right now I don't have a need for it but I think it would almost be a necessity for a three phase simulation if someone wanted to build one in the future. 

The only hiccup I can think of is that this might be a pain to implement in a backwards compatible way. Since in general the same phase could have multiple fluid-interfaces defined or the same fluid-interface defined differently for each network it is registered with or none at all if it's older code. It seems like you would run into an issue of where to look for a given interface property when a model such as capillary pressure is run.

I suppose storing any property that depends partially & totally on an interface property with the respective interface could resolve the issue. If multiple interfaces are defined on the phase then the same model would have to be used for all of them unless a specific interface is specified by a keyword arg. In addition to that I'd say a private `MainPhase - Air Interface` would need to be created internally to store the default properties that are currently stored on the phase now. That would be a start to maintaining backwards compatibility and retain pleasant default behavior for users in the future if they don't need to fully define the physics of an interface.

**Comment by jgostick** [comment]
Wow, thanks for the deep thoughts on this!  I hadn't really thought about backward compatibility, but I see your point.  I will take my rough idea and put it into PR so we can have some code to talk about.

**Comment by jgostick** [comment]
This idea, and associated PR, address the problems mentioned in #194 , so I'll close that one now.

**Comment by jgostick** [comment]
This is as nebulous and difficult as 'mixtures'.  I'm going to tag is as 'back burner' so we can think about it later.
