### ISSUE TITLE
Remove MatFile Network?

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#591]
I know this would be a backward incompatible change, but this Network class is only used by the UofT people.  It was made very specifically for their network extraction results.  Instead of removing it completely, we could at least not import it automatically, so that other users are fooled by it.  The actual matlab import class is in utilities.io.

**Comment by stadelmanma** [comment]
I'd say meet in the middle and move all the required code to generate the network to IO.py so your MatFile class looks kinda like 
```
class MatFile(GenericNetwork):
    (doc string stuff)
    def __init__(self, filename='', path='', **kwargs):
        self = OpenPNM.Utilities.IO.MAT.load(os.path.join(path, filename))

    (rest of the cleanup methods)
```
Throw in a deprecated warning and that would maintain full backwards compatibility until you reach a version you want to drop the class altogether. If it's only that one group using it then I'd say remove it sooner rather than later because it isn't a groundbreaking API change, aside from the cleanup performed automatically. When I first came into OpenPNM and needed to make a network import class this had me rather confused on where and how I was suppose to add a new import class.

**Comment by jgostick** [comment]
This class never should've been added to the code, but we were not really thinking 'big picture' enough back then.   We could move it to Utilities.IO, **AND** stopped automatically importing it...that would really hide it.

**Comment by jgostick** [comment]
I'm going to close this issue, and add a mention of it in the #491 issue regarding 2.0 changes.
