### ISSUE TITLE
Possible bug in subdivide?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#617]
It seems that when you try to subdivide two adjacent pores at once, the outcome is slightly different than when consecutively subdividing them. Here are two pictures for demonstration:

![capture](https://cloud.githubusercontent.com/assets/14086031/17297434/b592ccaa-57d3-11e6-9a70-0840613df7e5.PNG)

**Comment by maghighi** [comment]
The bug isn't that it does the connections in this way, the problem is that it allows the user to run the "subdivide" method more than once. The user should choose the candidate pores at the beginning.  Creating the new connections between different scales (spacing) makes the code extremely complicated and even slower. So, in the new version, the user won't be able to do this. For now, I'll probably add something to raise an error.
