### ISSUE TITLE
Storing phase properties that pertian to a combination of phases

### ISSUE THREAD

**Issue by MichaelHoeh** [PMEAL/OpenPNM#625]
When two phases are defined, i.e. Air and Water, then currently the surface tension of the Air-Water-System is stored only on the Water phase. This property is used in calculating the entry capillary pressures for the percolation simulation by adding a model to the physics object, like:

phys_water = op.Physics.Standard(network=pn,phase=water,geometry=geom)
phys_water.models.add(propname='throat.capillary_pressure', model=mod)

This is fine and puts the computed capillary pressures on the network, as the surface tension of water is found. If water is the invading fluid, as in fuel cells, everything is fine.

But for air to be the invading fluid, the capillary pressures have to be on the air physics object, if I see it correctly. Yet running

phys_air = op.Physics.Standard(network=pn,phase=air,geometry=geom)
phys_air.models.add(propname='throat.capillary_pressure', model=mod)

gives a key error:

KeyError: 'pore.surface_tension'

This can be alleviated by doing

air['pore.surface_tension'] = water['pore.surface_tension']

which is not ideal and therefore there should be a proper handling of this.

I suggest having the following:
- if property not found - check other phases that are defined on the network for property

In the end surface tension is a property of two fluids, not just a single fluid, and therefore if the combination of the two fluids is set on the network, OpenPNM should be able to put together.

I would like to hear your thoughts on how to handle it, and I will be happy to work on this.

**Comment by jgostick** [comment]
Interesting..sorry we didn't talk about this during today's telecon.  I don't think that having one phase grab properties from another is a safe approach though, since this could lead to grabbing water viscosity when you forget to define air viscosity.  We have been kicking around the idea of an Interface class ( #581 ).  The point would be to instantiate an interface object by passing in the network plus two phases.  Then you could assign things like surface tension to it...but could also have pore scale models for calculating the air-water surface area.

**Comment by MichaelHoeh** [comment]
I see your point, and I agree that it is unsafe, and could mess things 
up, if one is not paying attention. I think the interface class is the 
best way to go with this issue. Thanks for clarifying.

**Comment by jgostick** [comment]
This issue is related to PR #583 and also discussed in issue #581 and #194
