### ISSUE TITLE
Error regarding air displacing water process

### ISSUE THREAD

**Issue by JiyuanZhang221** [PMEAL/OpenPNM#643]
Hi everyone,

I came across with a problem when performing air displacing water drainage, which displays as:

... OpenPNM/Base/__Core__.py,  line 926, in _interleave_data
raise KeyErro(prop)
KeyError: 'pore.surface_tension'

-----------------------------------------------------------
The code is:

import OpenPNM as op
pn=op.Network.Cubic(shape=[50,20,20],spacing=0.0002)
pn.add_boundaries()

Ps=pn.pores('*boundary')
boun=op.Geometry.Boundary(network=pn,pores=Ps)
Ps=pn.pores('internal')
Ts=pn.throats()
geom=op.Geometry.Cube_and_Cuboid(network=pn,pores=Ps,throats=Ts)

#geom.plot_histograms() #inspection of pore and throat geometries

Wa=op.Phases.Water(network=pn)
Ar=op.Phases.Air(network=pn)

phys = op.Physics.GenericPhysics(network=pn,pores=pn.Ps,throats=pn.Ts,phase=Ar)

mod=op.Physics.models.capillary_pressure.improved_model
phys.add_model('throat.capillary_pressure', model=mod)

MIP=op.Algorithms.Drainage(network=pn)
MIP.setup(invading_phase=Ar, defending_phase=Wa)

MIP.set_inlets(pores=pn.pores('*boundary'))
MIP.run()

MIP.plot_drainage_curve()
data_wash=MIP.get_drainage_data()
-----------------------------------------------------------------

Anybody knows how to fix the problem? 

Thanks.

**Comment by MichaelHoeh** [comment]
This problem is known, and discussed in #625, and as well in #583 and also in issue #581 and #194. Essentially, it breaks because the surface tension is only stored on one of the two phases, but it essentially an interface property. The only clean way to resolve this is the potential interface class, which is supposed to come in V2.0. For a hack around it, check #625.

**Comment by JiyuanZhang221** [comment]
Thanks. It works  according to previous suggestions.
