### ISSUE TITLE
Telecon Agenda for January 18th, 2017

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#668]
1. How to deal with contributed algorithms:  @stadelmanma has contributed a nice dynamic IP algorithm, but I am reluctant at merge it directly (too hard to maintain going forward).  Is there a better way?
2. Gitter is now shut down, and the Q&A page on the openpnm site is running (openpnm.org is running on a new server so should stop crashing).
3. Relax the number of arguments during obejct init? Especially the Algorithms. The GenericLinearTransport assumes only one phase is relevant, but this may not always be true.

**Comment by stadelmanma** [comment]
Since I won't be able to make the telecon, instead of merging the code directly we could try making it a sub-module, I don't know if that is the best route.

 I suppose the other option is to make a user-contrib algorithms folder and stick it in that. You'd then just stick an appropriate warning saying these may or may not work with the current version of OpenPNM and are maintained by third parties. There may be a way to config your CI process to test those "user-contrib algorithms" but instead of causing the build to fail just output a warning.  

https://github.com/blog/2104-working-with-submodules

**Comment by jgostick** [comment]
I'm thinking something like the OpenPNM-Examples repository, but maybe the OpenPNM-Algorithms?  Not totally sure how to merge just the algorithm though.  It really needs to be part of the whole code base.  Perhaps we could add a folder to the OpenPNM-Examples called "Classes" where the .py file is given?  This would be hard to test though. Argh.

**Comment by borahdj2010** [comment]
Is there a telecon today? I do not have much idea.  The OpenPNM examples definitely need more details. This is what I found as a beginner with absolutely no idea.
