### ISSUE TITLE
ImportError with OpenPNM 1.6.1

### ISSUE THREAD

**Issue by sj44585** [PMEAL/OpenPNM#701]
Hi,
 I have done a clean install of the version 1.6.1 on Winpython 3.4.4.2.  But when I type in 'import OpenPNM as op' in the python console it always pop out

   'Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\Desktop\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\OpenPNM\__init__.py", line 59, in <module>
    from . import Base
ImportError: cannot import name 'Base''
 
Could anyone please help me with this problem?

Regards
Jing

**Comment by jgostick** [comment]
Usually people get errors like this because of the capitalization in the package name, but in your case I can't really tell where the problem is.  Could you elaborate on what you mean by "clean install"?  Did you use ```pip install openpnm``` or are you trying to load a local version of the repo cloned from Github?  Also, we only support the latest version of Python, so try getting Python 3.6 and see if that helps.  I don't know why 3.4 wouldn't work but you never know.
