### ISSUE TITLE
A copied algorithm has no master

### ISSUE THREAD

**Issue by islah** [PMEAL/OpenPNM#710]
Hi,

I manually copy an algorithm since it's not included in the clone_simulation method. But then the copied algorithm cannot be simulated since it has no master (when running the models.add._find_master method).  Registering it to the controller (I'm using version 1.3) doesn't help. So, how to make the duplicate algorithm customizable?

Thanks,
Islah

**Comment by jgostick** [comment]
Hi @islah 
This 'master' business is a huge pain and kludgey mess on our part.  As you can see it's fragile and easy to break.  I'm not sure what you mean by copying an algorithm manually though.  Can you explain what you did and what you are trying to accomplish in a bit more detail?

**Comment by islah** [comment]
Hi,

Yeah, I have spent some time to work around this issue with no success. Below are the steps I do:

[1] alg = InvasionPercolation(...)
[2] alg_new = copy.deepcopy(alg)
[3] ctrl.update({ 'alg_new': alg_new })
[4] phys_water = alg._net._phases[0]._physics[0]
[5] phys_water.models.add(...)
[6] phys_water2 = alg_new._net._phases[0]._physics[0]
[7] phys_water2.models.add(...)

So I created an invasion algorithm and manually copy and register it (line1-3). Unlike the original one (line 4-5), this duplicate algorithm cannot be customized with adding the same model as in line 5 but with different parameters (line 6-7). The last line fails running the models.add._find_master method since ModelsDict has no master. 

The phys_water and phys_water2 have the same properties and values, but they are two different objects. So phys_water2 is somewhat a ghost object of the other (?).

**Comment by jgostick** [comment]
the copy and deep copy things don't work because they break the internal connections of OpenPNM.  Instead you should instantiate a new objects, then copy the desired properties.   For instance:

```
    alg = InvasionPercolation(...)
    alg_new = InvasionPercolation(...)
    alg_new.update(alg)  # This will copy all the props and labels from alg to alg_new
```

You can also copy the models from an existing object to a new one with:

```
    water2 = op.Phase.GenericPhase(net=pn)
    water2.models.update(water.models)
    water2.models.regenerate()
```

After you run the regenerate method the water2 dict will then be populated with numerical values coming out of the models. 

Similarly for phys_water2...make a new, empty, generic object associated with water2, then copy the dicts over.

We are currently working on a version 2.0 of OpenPNM and will be fixing the way this all works...we'd LOVE your input since it seems you've been using it fairly deeply.  Email me your thoughts at jgostick at uwaterloo.ca.

**Comment by islah** [comment]
I am aware of that breaking things inside so I registered the algorithm to the controller. Although it didn't work, I am still quite sure that the internal connection is kept by the controller. So, to avoid instantiating all new objects, I have just tried to register all of them (net_new, ..., phys_water_new, alg_new) to the controller. And it works!

Ok, I will email you later on.
