### ISSUE TITLE
export_data function in openpnm_v2 missing a **kwargs

### ISSUE THREAD

**Issue by magnaou** [PMEAL/OpenPNM#752]
The function "core.Workspace.export_data" is missing a "** kwargs" to pass the list of phases to the "io.VTK.save" function. It should look like:
"
def export_data(self, simulation, filename=None, fileformat='vtp', **kwargs):
...
        openpnm.io.VTK.save(simulation, filename=filename, **kwargs)
...
"
Another solution is forcing the "io.VTK.save" function to export the data of all the existing phases.
Thank you.
Mehrez

**Comment by jgostick** [comment]
Actually, for now I have removed the ability to pass phase data, since it is unclear how to name these arrays.  I think I used something like 'pore.water|temperature' and 'pore.air|temperature' before, but we should discuss how this should be handled...including how to read this back in from a saved file.

**Comment by jgostick** [comment]
i have 'readded' this during my flurry of IO changes last weekend
