### ISSUE TITLE
Reimplement neumann_group

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#768]
This could be done as super pore again, or by removing a line and replacing it with the group balance equation.  The second option gets rid of the super-pore thing.

**Comment by jgostick** [comment]
If we go with the super pore approach, it should be called 'virtual pore'

**Comment by ma-sadeghi** [comment]
Just for the record, what was the main problem (pain point) for the super pore approach in v1? @jgostick @maghighi

**Comment by jgostick** [comment]
Nothing really....I just didn't get it into the new version yet because it's quite complex how it works.  The 'pain point' is that you have to increase the size of the array by one row to accommodate the new balance, which means adding a new 'virtual pore', which then required virtual throats with some specified value of conductance.  This virtual business seemed a bit arbitrary to me, so I thought we should revisit this to make sure it's the best approach.

The other way would be this following:

1.  Say you want flux from pores 1, 2, and 3 to equal n_t, you create an equation: n_t = n_1 + n_2 + n_3 (where n_1, n_2 and n_3 can be written as sum(g*(x_1 - x_i)) where i is a neighbor).
2. Instead of adding this equation to the array, you could actually remove the balance equation for n_1 (or n_2 or n_3) and replace it with n_t.  Clearly n_t is a linear combination of the three balance equations for n_1, n_2 and n_3, so you'd need to remove just one.

In practical terms, the virtual pore is probably easier since it wouldn't break the boundary conditions or source terms functions, which reach into the array and alter things, so if equations start to get deleted this would break things.  Based on this logic alone, I think virtual pore is better.

**Comment by ma-sadeghi** [comment]
But n_1, n_2, and n_3 all depend on the concentration of the super pore, let's say c_s. How would you find c_s?

**Comment by maghighi** [comment]
Let’s assume:
Sum(g*(x_1 - x_i)) = n1,
Sum(g*(x_2 - x_i)) = n2,
Sum(g*(x_3 - x_i)) = n3
n1 + n2 + n3 = NG
So, we can replace any of the first 3 with the last one. The problem is the values of n1, n2 and n3. If we have super pore, then they are all zeros. Let’s replace the equation1 with the last one, so what are the values of n2 and n3 for the second and the third rows of RH-side matrix? If we say they are zeros, then it means n1 = NG which is kind of unrealistic assumption. However, in case of super pore:
Sum(g*(x_1 - x_i)) = 0,
Sum(g*(x_2 - x_i)) = 0,
Sum(g*(x_3 - x_i)) = 0,
g_SP*(x_SP - x_1) + g_SP*(x_SP - x_2) + g_SP*(x_SP - x_3)  = NG
By using Super Pore, we do not have the mentioned problems, since in here:
N = n1 + n2 + n3 = 0 (non-reaction)
N = (n1_in + n2_in + n3_in) - (n1_out + n2_out + n3_out)
NG != n1 + n2 + n3,
NG = alpha * (n1_in + n2_in + n3_in), where alpha [a1, a2, a3] is the portion of the NG that each pore receives (through super pore throats).

**Comment by jgostick** [comment]
OK, so the super pore (or I prefer virtual pore) is needed, and also happens to be the best/easiest way to implement this.  Now we just need to find the time to do it.
