### ISSUE TITLE
make new packages: OpenPNM-materials

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#782]
This was proposed as a way to:
(a) Prevent cluttering up the core openpnm package
(b) Encourage people to submit both materials recipes and pore-scale models since it could be VERY clearly documented how to submit something to either repo.

**Comment by ma-sadeghi** [comment]
I'm for `openpnm-materials`, but still not 100% sold on `models` module. `materials` seems more logically disconnected to `openpnm`, but `models` goes hand to hand with it. Plus, I think it's less likely that someone wants to contribute to `models`, rather they expect `openpnm` to have it built-in, whereas `openpnm` not having `materials` built-in is more argueable since everyone could be working with a custom-made material.

**Comment by jgostick** [comment]
We're going to do materials, but not models.
