### ISSUE TITLE
Why not `models` know if they're being applied to a `pore` or `throat`?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#797]
Right now, I'm implementing Knudsen diffusion model and so far, I ended passing the default argument since the model doesn't know if it's being added to pores or throats. Here's what the script looks like:

```
knudsen_scaling = pnm.physics.models.knudsen.knudsen_scaling
phys_water.add_model(propname='pore.mixed_diffusivity', model=knudsen_scaling,
                     diffusivity='pore.diffusivity')
phys_water.add_model(propname='throat.mixed_diffusivity', model=knudsen_scaling,
                     diffusivity='throat.diffusivity')
```
It would be good if the model had this knowledge. By the way, this problem comes from the fact that Knudsen diffusivity cannot be interpolated from pore data. Here's how the code would look like ideally:

```
knudsen_scaling = pnm.physics.models.knudsen.knudsen_scaling
phys_water.add_model(propname='pore.mixed_diffusivity', model=knudsen_scaling)
phys_water.add_model(propname='throat.mixed_diffusivity', model=knudsen_scaling)
```

**Comment by jgostick** [comment]
In your second case, you still need to have diffusivity as an argument so the user can specify which diffusivity to use ('diffusivity_1', diffusivity_guess', etc), so you also have the option to pass in 'pore' or 'throat' diffusivity, which controls the size of the returned values.  This is less convenient, but more flexible.  It makes less sense here, since there is usually only one diffusivity, but in hydraulic conductance models there could be many ways to specify the hydraulic diameter to use, so the user needs the ability to pass their own custom defined hydraulic diameter keys.
