### ISSUE TITLE
random seed model is not working well

### ISSUE THREAD

**Issue by jgostick** [PMEAL/OpenPNM#818]
It doensn't behave when setting the seed to a constant value, and now it seems that it doesn't obey the upper and lower limit values.

**Comment by magnaou** [comment]
The scipy.random.seed was overridden within models.misc.random with seed=None.
 I fixed this with an if condition and pushed to dev-V2-alpha1.
It seems that it's working now.

PS: keep in mind that to make the "scipy.random.rand" reproducible, the "scipy.random.seed" has to be called again each time "scipy.random.rand" is used.
Example:
>>> import scipy as sp
>>> sp.random.seed(0)
>>> sp.random.rand(5)
array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ])
# if "sp.random.seed" is not called again, the random generation will be different:
>>> sp.random.rand(5)
array([ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152])
# now, if we reset the seed value, it will work
>>> sp.random.seed(0)
>>> sp.random.rand(5)
array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ])

**Comment by magnaou** [comment]
@jgostick it appears that we have another bug when doing "geom.models.dependency_tree()" now. Indeed, if you reset the seed with "sp.random.seed(mySeed)" and then run "geom.models.dependency_tree()", the "geom['pore.seed']" array doesn't change as we expect, however, other quantities ("geom['pore.diameter']", "geom['pore.volume']", etc) change.
Is that caused by the "dependency tree" list not being in the right order?

**Comment by magnaou** [comment]
We need to check if setting the random.seed in a global way (i.e., set the seed value only once and make numpy always use it without having to recall it each time random.ran is used) can solve the problem.
I will check and let you know.

**Comment by jgostick** [comment]
If this is fixed, then I will uncomment the tests for it and see how it goes.
