### ISSUE TITLE
Logger - how does it now work and do we need it? If we do, do we need to use it for errors?

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#867]
In V2 I've now come across two ways of loading the logger. Which is correct?

from openpnm.core import logging as _logging
_logger = _logging.getLogger(__name__)

import logging

Logger is useful for tracking progress for info. I never use it for debug, error would be better handled as letting the code throw an exception - this points the console directly to the fault. Similarly I noticed now in V2 the use of try and except has been massively scaled down. There probably isn't a good genuine use case for them.

**Comment by jgostick** [comment]
The logger was highly motivated by andreas.  I almost never refer to them, but maybe because we didn't write them in a way that is helpful?  

Anyway, the debug level is information overload, the warnings are confusing for new users (ie they could most be ignored), and errors are best handled by exceptions.

The only use case I can think of is to output the progress of algorithms using the info level.  This way people could optionally turn on/off the messages, and they would also be nicely / consistently formatted.  

 I actually think removing the logger entirely might not be a terrible idea.  I wonder if it would help performance?  Like the debug message get called all the time, just not displayed.

**Comment by TomTranter** [comment]
I think we're pretty much agreed then that the only thing it's really useful for is sparingly given progress info. Leaving it in would be my preference. If people want to add debug messages when they are debugging that's fine (although debugging interactively is usually how I do it) but they should not be left in production code and certainly shouldn't be getting called when not displayed

**Comment by TomTranter** [comment]
I wonder whether keeping a string of text in memory and adding to it then printing to a log file at the end would be useful if someone did want to track exactly what was going on. Ansys and Comsol provide such logs as .out files. Writing all in one go at the end would be quicker or maybe when the memory reaches a certain size. Just a thought. I can empathize with Andreas that they have their uses
