### ISSUE TITLE
Why Boundary class takes `shape` as argument?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/OpenPNM#954]
Probably for calculating `throat.area` and `throat.length`. But shouldn't the boundary pores/throats impose 0 resistance, i.e. `throat.length` = 0?

**Comment by jgostick** [comment]
It looks like this shape is used to choose between cubic and spherical pores.  It's not a good choice of keyword though since this usually means array shape, like [5, 5, 5]

**Comment by jgostick** [comment]
Maybe this could be buried in the settings?  like:

`boun = op.geometry.Boundary(network=pn, settings={pore_shape:'sphere', throat_shape:'cube'})`

This would require a bit of work on the back end however, since users would expected to be able to change the setting, then regenerate models and see the changes.

**Comment by jgostick** [comment]
we should remove the argument, assume spheres and cylinders...then we can RE-ADD some way to specfify this, which will not be a breaking change.  That is, someone who has been relying on this argument won't find it disappeared.
