### ISSUE TITLE
Hydraulic conductance model uses network._shape which is not always there

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/OpenPNM#964]
I just found this bug after updating the examples to use the new master V2 branch. The statoil_import_and_permeability_calculation imports a network and it doesn't have the _shape attribute. We should probably put a property on Generic network and overload it for the different networks or change the logic of the conductance model

**Comment by TomTranter** [comment]
A pore_seed model also uses ._shape and it only appears to be defined for cubic networks. It doesn't make sense for imported or random networks so I would suggest changing the models and removing the ._shape attribute everywhere. The hydraulic conductance model seems to be just changing a constant value so perhaps that could become a parameter

**Comment by TomTranter** [comment]
@ma-sadeghi I assigned this to you as you changed the model last. What is the logic behind the is2d part of the model? Is it really necessary and can you explain the change in constant?

**Comment by ma-sadeghi** [comment]
@TomTranter Sorry my bad, I entirely forgot `_shape` is only available in `Cubic` networks. I put it to support 2d simulations. Either we can add a parameter to let the model know if it's 2d or 3d, or we can have two different models like `hagen2d' and `hagen3d`. What do you think?

**Comment by ma-sadeghi** [comment]
We could also add it to `network.settings` maybe?

**Comment by TomTranter** [comment]
Do you mean where geometry is actually 2d? Rather than pseudo-2d like we currently have it being one pore thick. All our models are 3d and it think supporting 2d simulations properly (if we think it's useful) would take a bit more work and probably a separate set of models. Introducing if statements to all the current ones doesn't seem like the way to go. I don't know if you have already discussed this with @jgostick . Alternatively is could become part of a shape factor model which we could/should be applying to all conductance models.

**Comment by ma-sadeghi** [comment]
Yep, an actual 2d simulation. I agree that putting `if` statements in all our models is not a good idea. For the most part, we don't need to. All our conductance models (except hydraulic conductance) support 2d and 3d without explicit intervention, given that the passed arguments such as 'throat.equivalent_area', etc. account for the `2d`ness. The only problem (so far, maybe other models turn out to be the same) is that the hydraulic conductance model needs two separate equations for 2d and 3d simulations. I discussed this with @jgostick very briefly, so don't know what he thinks. As for other models (`pore_volume`, `throat_volume`), I made new models to support `2d` rather than putting `if` statements. We could do the same for hydraulic conductance. But, this whole thing definitely requires more thought. 

Encapsulating the correction terms in `shape_factor` sounds good, but then we'd need to write a whole bunch of models to calculate the `shape_factor`.

**Comment by TomTranter** [comment]
To be honest I'm not sure this a road we should be going down... What was the motivation behind these 2d models? With other cfd packages, it's either not possible or requires starting the simulation in a different mode as it changes so many things. To do it properly we'd probably need a bunch of multiphase models which certainly wouldn't just be different by a constant. As the strength of openpnm is for 3d tomography it doesn't seem like it would be worth the development effort....

**Comment by ma-sadeghi** [comment]
I guess the motivation was to use it as a toy model for prototyping the dispersion algorithm. I think - and I might as well be wrong - that they have a few advantages over 3D models when prototyping: they're easier to visualize in-place and the results are easier to verify with intuition. I don't know yet if other models are required to be rewritten or tailored to accommodate 2D, but as I said, conductance models need not be changed. They only new models I've added are in geometry such as `circle` as the 2d version of `sphere` for `pore.volume`, etc.

Anyways, I think if it's only adding a few models in `geometry` module, there's no harm in keeping them. In case we need to add a whole bunch of other models to accommodate true 2d simulations, then I agree that it might not be worth our time, nor is our priority at the moment.

**Comment by TomTranter** [comment]
Ok, well, for now can you address the references to ._shape in the code. It would be good to get these examples updated asap. Cheers

**Comment by TomTranter** [comment]
@ma-sadeghi I think the conductance models need to be more robust. The equivalent_area and conduit_lengths are only defined on StickAndBall. What about when you apply these models to any other geometry. There is no error handling that I can see. If the equivalent area is to be the default then if it's not found but the area is then I would expect it to use that.

**Comment by TomTranter** [comment]
There is also a problem that geom models may actually reside on the network. The statoil example is still breaking but it's because the physics model has been added to a phase and is looking for a geom when the info is on the network - I've raised a new issue to discuss this #966

**Comment by jgostick** [comment]
Wow, that's a long discussion to catch up on!  Here are my thoughts:
* I think amin justified the use of 2D models quite well.  We should support them since it's not too much trouble
* As for shape of the network, you can find 2D-ness other ways (checking that one of the coord axis has only one unique value).  BUT I don't think we should check it ... see next 2 comments
* Having models with 2D if statements in them is bad 
* Adding additional models with 2D in the name where necessary is ok with me
* Tom is correct that the conductance models must be robust enough for all networks, but this puts us in a tough spot, because our new definition of pore_area is complex.  Basically, any imported networks will need to have OUR throat.equivalent_area method added to it!

**Comment by TomTranter** [comment]
Can we change back to using the old area but handle when the data is of the equivalent form by parsing it in all the conductance models

**Comment by jgostick** [comment]
Hey @ma-sadeghi , we need to change the phase to target in these physics models, and get the geometrical data from the network (relying on interleave data), then they'll be general?
