### ISSUE TITLE
Methane properties

### ISSUE THREAD

**Issue by sukrumerey** [PMEAL/OpenPNM#974]
Hi Dear All
I want to define Methane properties. From where I should start to add this module?

**Comment by ma-sadeghi** [comment]
Hi @sukrumerey !
First of all clone the `dev` branch from the main GitHub page of `OpenPNM`. It's much easier if you use a Git GUI like [GitKraken ](https://www.gitkraken.com/) or [SourceTree](https://www.sourcetreeapp.com/). 
Then, create a new branch off of the `dev` branch which you just cloned. You can name it whatever you want, say `add_methane`. Once you're in the this new branch, create a new file in `OpenPNM/openpnm/phases` and name it `Methane.py`. For convenience, you can copy one of our built-in `phases` such as `Air.py` and rename it to `Methane.py`. Then change `Methane.py` accordingly. Once you're done, go to `OpenPNM/openpnm/phases/__init__.py` and add this line:
```
from .Methane import Methane
```
Note: inside `Methane.py` make sure to change the class name to `Methane` as well.

Now commit your changes either through Git command line or the GUI of your choice. Make sure that you're checked in the newly created branch `add_methane`. Then, push your changes to the branch and finally create a pull request on GitHub. If you install GitKraken, you can easily create the pull request in the application. Make sure to change the destination of your pull request to the `dev` branch, rather than `master`. `master` contains the latest stable version of the code and we don't want to directly commit to that. Instead, any changes/improvements/features should first be pushed to a new branch (in your case `add_methane`), then PR'ed (pull requested) onto the `dev` branch, and once we have a significant batch of changes/improvements/features, those changes will be pushed to the `master` branch and a new (minor) version is released.

Congratulations! You've just created your first pull request in our repository! Feel free to ask any question that you might have :)

**Comment by jgostick** [comment]
This is a great how-to do a PR....we should add this to the documentation on dev_guide or something, the point people there.  @sukrumerey might be looking for a more gentle introduction though, so I'll add a bit:

In your run_script, create a Phase object based on GenericPhase like this: 

`ch4 = op.phases.GenericPhase(network=pn)  # assuming your network is named pn`

Then you have an empty object with no property models, so you need to add them.  Let's say you want to add a viscosity model, you'd do this:

`ch4.add_model(propname='pore.viscosity', model=op.models.misc.polynomial, a = [1, 2, 3], prop='pore.temperature')`

This assumes that you have a viscosity model that is a second order function of temperature, with coefficients a0=1, a1=2 and a2=3.  The models.misc folder contains a few functions that can be used for such correlations, but you need to know the coefficients.  

If you want to do something more serious like use the peng-robinson equation of state the you need to write your own model.  I will point you to the [docs on this](http://openpnm.readthedocs.io/en/master/userguide/customizing.html).  Let us know how it goes.

BTW, the approach suggested by @ma-sadeghi above is great if you plan to use methane a lot, so it's always there for you and can be created with one line (`ch4 = op.phases.Methane(network=pn)`).

**Comment by sukrumerey** [comment]
Dear @jgostick and @ma-sadeghi 

Thank you all very much for your help. I want to develop methane code including EOS calculations. Actually I had written some in matlab and need to convert it to python language.  I guess I should focus on "customizing" to add it to OpenPNM.
Regards

Sukru

**Comment by jgostick** [comment]
Hi @sukrumerey I will add a few more note here.  We have an open PR that incorporate Cantera into OpenPNM for complex property calculations (#857).  This will probably make it into the code in V2.1 or 2.2...so several months from now.  We also plan to add more functional options into the model.misc folder (#976).  

I will close this issue for now, since I think we've given you the best advice we can.  If you run into other problems we can either reopen this issue, or start a new one.
